#!/usr/bin/env bash
#
# bootstrap
#
# This script will pull down the latest versions of the dotfiles and copy them
# to your home directory.

install_dotfiles() {
  rsync -av \
    --exclude ".DS_Store" \
    --no-perms \
    --quiet \
    ./home/ ~
}

PROG=${0##*/}

# Check for git.
command -v git >/dev/null 2>&1 || { echo "$PROG: git: command not found"; exit 1; }

# Pull down the latest changes.
echo "Syncing dotfiles..."
cd "$(dirname "${BASH_SOURCE}")"
git pull origin master

# Verify that the user wants to continue before potentially overwriting files.
read -p "This may overwrite existing files. Are you sure? (y/n) " -n 1
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  install_dotfiles
  source ~/.bash_profile
fi
