#!/usr/bin/env bash
#
# afdownsample - audio file downsample
#
# Downsample high resolution audio files to 16 bit/44.1 kHz. Audio files with
# a bit depth of 24 and a sample rate greater than or equal to 44.1 kHz are
# seen as high resolution. The audio file formats AIFF, FLAC and WAV are
# supported.
#
# SoX (http://sox.sourceforge.net) is used as the sample rate converter.
#
# By default, high resolution audio files in the current working directory
# will be downsampled. Use the option -d to specify a directory that holds
# high resolution audio files. Downsampled files will be written to the
# directory OUT in the current working directory.


usage() {
    echo "usage: $PROG [-d directory]"
}


COUNT=0
CWD="$(pwd)"
DIR="."
PROG=${0##*/}

# Parse command line options.
OPTIND=1
while getopts :d:h OPT; do
    case $OPT in
        d)
            DIR=${OPTARG%/}
            ;;
        h)
            usage
            echo
            echo "  -d  Directory with high resolution audio files"
            exit 0
            ;;
        \?)
            echo "$PROG: illegal option -- $OPTARG"
            usage
            exit 1
            ;;
        :)
            echo "$PROG: -$OPTARG requires an argument"
            usage
            exit 1
            ;;
    esac
done
shift $((OPTIND-1))

if [[ $# -gt 0 ]]; then
    echo "$PROG: illegal argument -- $1"
    usage
    exit 1
fi

# Check for sox.
command -v sox >/dev/null 2>&1 || { echo "$PROG: sox: command not found"; exit 1; }

# Check if directory exists.
[[ -d "$DIR" ]] || { echo "${PROG}: ${DIR}: No such directory"; usage; exit 1; }

# Trap interrupt.
trap 'echo aborting...; exit 3' SIGINT

while IFS= read -r -d '' file; do
    # Only downsample high resolution audio files.
    if [[ $(sox --i -b "$file") -eq 24 ]] && [[ $(sox --i -r "$file") -ge 44100 ]]; then
        if [[ $COUNT -eq 0 ]]; then
            mkdir -p OUT || exit 1
        fi

        # Very high quality linear phase (-v -s) with automatic TPDF dither.
        sox -S "$file" -b 16 --comment "" OUT/"${file##*/}" rate -v -s 44100 || exit 2

        # Apply noise-shaping dither.
        #sox -S "$file" -b 16 --comment "" OUT/"${file##*/}" rate -v -s 44100 dither -s || exit 2

        # Use this if any clipping has occured.
        #sox -S "$file" -b 16 --comment "" OUT/"${file##*/}" gain -1 rate -v -s 44100 || exit 2

        COUNT=$((COUNT+1))
    fi
done < <(find "$DIR" -depth 1 -type f \( -iname "*.aiff" -or -iname "*.aif" -or -iname "*.wav" -or -iname "*.flac" \) -print0)

if [[ $COUNT -eq 0 ]]; then
    echo "$PROG: No high resolution audio files found"
fi
