#!/usr/bin/env bash
#
# osx-defaults
#
# Set reasonable OS X defaults.
#
# Thanks to Mathias Bynens' OS X defaults script:
# - https://github.com/mathiasbynens/dotfiles/blob/master/.osx

PROG=${0##*/}

# OS X only...
if [[ $(uname) != "Darwin" ]]
then
  echo "$PROG script is for OS X only!"
  exit 1
fi

# OS X El Capitan only...
if ! [[ $(sw_vers -productVersion) =~ ^10\.11\..+ ]]
then
  echo "$PROG script is intended for OS X versions 10.11.x"
  exit 1
fi

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Security
# ----------------------------------------------------------------------------

# Disable Gatekeeper
# Allows installing apps from anywhere
sudo spctl --master-disable

# Sharing
# ----------------------------------------------------------------------------

# Set computer name (as done via System Preferences → Sharing)
sudo scutil --set ComputerName "Fuzza"
sudo scutil --set HostName "Fuzza"
sudo scutil --set LocalHostName "Fuzza"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "Fuzza"

# General
# ----------------------------------------------------------------------------

# Set Sidebar icon size to small.
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -integer 1

# Save new documents to disk (not to iCloud) (default: not set).
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -boolean false

# Report computer name, OS X version and IP address when clicking the clock
# in the Login window (default: not set).
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

# Desktop & Screen Saver
# ----------------------------------------------------------------------------

# Disable shadows on screen captures (default: not set).
defaults write com.apple.screencapture disable-shadow -boolean true

# Dock
# ----------------------------------------------------------------------------

# Minimize windows using the "Scale" effect.
defaults write com.apple.dock mineffect scale

# Finder
# ----------------------------------------------------------------------------

# Set default Finder location to home folder (~/)
defaults write com.apple.finder NewWindowTarget -string "PfLo" && \
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}"

# Show status bar.
defaults write com.apple.finder ShowStatusBar -bool true

# Show path bar.
defaults write com.apple.finder ShowPathbar -bool true

# Safari
# ----------------------------------------------------------------------------

# Disable opening "safe" files automatically after downloading.
#defaults write com.apple.Safari AutoOpenSafeDownloads -boolean false

# Set home page to `about:blank`.
#defaults write com.apple.Safari HomePage -string "about:blank"

# Do not automatically update extensions.
#defaults write com.apple.Safari InstallExtensionUpdatesAutomatically -boolean false

# Show status bar.
#defaults write com.apple.Safari ShowStatusBar -boolean true

# Terminal
# ----------------------------------------------------------------------------

# Add terminal profiles for the Solarized Dark and Solarized Light color
# schemes.
open "../terminal/Solarized Dark.terminal"
sleep 1
open "../terminal/Solarized Light.terminal"
sleep 1

# Make Solarized Light the default terminal profile.
defaults write com.apple.Terminal "Default Window Settings" -string "Solarized Dark"
defaults write com.apple.Terminal "Startup Window Settings" -string "Solarized Dark"

# Other
# ----------------------------------------------------------------------------

# Use plain text mode for new TextEdit documents
defaults write com.apple.TextEdit RichText -int 0

# Avoid creating .DS_Store files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Disable disk image verification
defaults write com.apple.frameworks.diskimages skip-verify -bool true && \
defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true && \
defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

###############################################################################
# Kill affected applications                                                  #
###############################################################################

for app in "Dock" \
  "Finder"; do
#"Terminal" \

	killall "${app}" &> /dev/null
done

# for app in "Activity Monitor" "Address Book" "Calendar" "Contacts" "cfprefsd" \
# 	"Dock" "Finder" "Google Chrome" "Google Chrome Canary" "Mail" "Messages" \
# 	"Opera" "Photos" "Safari" "SizeUp" "Spectacle" "SystemUIServer" "Terminal" \
# 	"Transmission" "Tweetbot" "Twitter" "iCal"; do
# 	killall "${app}" &> /dev/null
# done
echo "Done. Note that some of these changes require a logout/restart to take effect."
