#!/usr/bin/env bash
#
# osx-defaults
#
# Set reasonable OS X defaults.
#
# Thanks to Mathias Bynens' OS X defaults script:
# - https://github.com/mathiasbynens/dotfiles/blob/master/.osx


PROG=${0##*/}

# OS X only...
if [[ $(uname) != "Darwin" ]]; then
    echo "$PROG script is for OS X only!"
    exit 1
fi

# Ask for the administrator password upfront.
sudo -v


# General - UI/UX
# ----------------------------------------------------------------------------

# Set hostname. Only the user-friendly name (computer name), the local
# (Bonjour) host name and NetBIOS name get set by the Sharing preference pane.
sudo scutil --set ComputerName titan
sudo scutil --set LocalHostName titan
sudo scutil --set HostName titan
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "titan"

# Disable open and close window animations (default: not set).
defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -boolean false

# Report computer name, OS X version and IP address when clicking the clock
# in the Login window (default: not set).
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

# Easy access to the airport command line utility.
sudo ln -s /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport /usr/sbin/airport


# Desktop & Screen Saver
# ----------------------------------------------------------------------------

# Disable shadows on screen captures (default: not set).
defaults write com.apple.screencapture disable-shadow -boolean true


# Dock
# ----------------------------------------------------------------------------

# Set the icon size of Dock items to 48 pixels (default: not set).
defaults write com.apple.dock tilesize -integer 48


# Finder
# ----------------------------------------------------------------------------

# Enable text selection in Quick Look (default: not set).
defaults write com.apple.finder QLEnableTextSelection -boolean true


# Safari
# ----------------------------------------------------------------------------

# Disable thumbnail cache for History and Top Sites (default: not set).
defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -integer 2


# Terminal
# ----------------------------------------------------------------------------

# Add terminal profiles for the Solarized Dark and Solarized Light color
# schemes.
open "../terminal/Solarized Dark.terminal"
sleep 1
open "../terminal/Solarized Light.terminal"
sleep 1

# Make Solarized Light the default terminal profile.
defaults write com.apple.terminal "Default Window Settings" -string "Solarized Light"
defaults write com.apple.terminal "Startup Window Settings" -string "Solarized Light"


# Google
# ----------------------------------------------------------------------------

# Disable Google Software Update from checking for updates (default: 18000).
defaults write com.google.Keystone.Agent checkInterval 0


# Pixelmator
# ----------------------------------------------------------------------------

# Don't show the Welcome window on launching the application (default: false).
defaults write com.pixelmatorteam.pixelmator dontShowWelcomeScreen -boolean true
