#!/usr/bin/env bash
#
# osx-defaults
#
# Set reasonable OS X defaults.
#
# Thanks to Mathias Bynens' OS X defaults script:
# - https://github.com/mathiasbynens/dotfiles/blob/master/.osx


PROG=${0##*/}

# OS X only...
if [[ $(uname) != "Darwin" ]]; then
    echo "$PROG script is for OS X only!"
    exit 1
fi

# Ask for the administrator password upfront.
sudo -v


# General - UI/UX
# ----------------------------------------------------------------------------

# Set hostname. Only the user-friendly name (computer name), the local
# (Bonjour) host name and NetBIOS name get set by the Sharing preference pane.
sudo scutil --set ComputerName titan
sudo scutil --set LocalHostName titan
sudo scutil --set HostName titan
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "titan"

# Disable open and close window animations (default: not set).
defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -boolean false

# Set Sidebar icon size to small.
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -integer 2

# Report computer name, OS X version and IP address when clicking the clock
# in the Login window (default: not set).
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

# Disable daily summary of power usage statistics on OS X Mavericks 10.9.0.
if [[ $(uname -r) == "13.0.0" ]]; then
    sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.systemstats.daily.plist
fi


# Desktop & Screen Saver
# ----------------------------------------------------------------------------

# Disable shadows on screen captures (default: not set).
defaults write com.apple.screencapture disable-shadow -boolean true


# Dock
# ----------------------------------------------------------------------------

# Minimize windows into their application icon.
defaults write com.apple.dock minimize-to-application -boolean true

# Set the icon size of Dock items to 48 pixels (default: not set).
defaults write com.apple.dock tilesize -integer 48


# Finder
# ----------------------------------------------------------------------------

# New windows show home directory.
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/"

# Enable text selection in Quick Look (default: not set).
defaults write com.apple.finder QLEnableTextSelection -boolean true

# Show icons on the desktop for external disks.
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -boolean true

# Show icons on the desktop for removable media.
defaults write com.apple.finder ShowRemovableMediaOnDesktop -boolean true

# Show status bar.
defaults write com.apple.finder ShowStatusBar -boolean true


# Safari
# ----------------------------------------------------------------------------

# Disable opening "safe" files automatically after downloading.
defaults write com.apple.Safari AutoOpenSafeDownloads -boolean false

# Disable thumbnail cache for History and Top Sites (default: not set).
defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -integer 2

# Set home page to `about:blank`.
defaults write com.apple.Safari HomePage -string "about:blank"

# Do not automatically update extensions.
defaults write com.apple.Safari InstallExtensionUpdatesAutomatically -boolean false

# Show status bar.
defaults write com.apple.Safari ShowStatusBar -boolean true


# Terminal
# ----------------------------------------------------------------------------

# Add terminal profiles for the Solarized Dark and Solarized Light color
# schemes.
open "../terminal/Solarized Dark.terminal"
sleep 1
open "../terminal/Solarized Light.terminal"
sleep 1

# Make Solarized Light the default terminal profile.
defaults write com.apple.terminal "Default Window Settings" -string "Solarized Light"
defaults write com.apple.terminal "Startup Window Settings" -string "Solarized Light"


# Google
# ----------------------------------------------------------------------------

# Disable Google Software Update from checking for updates (default: 18000).
defaults write com.google.Keystone.Agent checkInterval 0

# Disable Google Software Update agent.
launchctl unload -w ~/Library/LaunchAgents/com.google.keystone.agent.plist


# Pixelmator
# ----------------------------------------------------------------------------

# Don't show the Welcome window on launching the application (default: false).
defaults write com.pixelmatorteam.pixelmator dontShowWelcomeScreen -boolean true
